---
# tasks file for mongodb
- name: Add repository
  yum_repository:
    name: mongodb
    description: Add mongodb YUM repo
    baseurl: https://repo.mongodb.org/yum/amazon/2013.03/mongodb-org/3.4/x86_64/
    keepcache: 0
    gpgcheck: no

- name: Install mongodb
  yum: pkg={{item}} state=present
  with_items:
    - mongodb-org
  notify: restart mongod



