---
- name: AWS scrapy VPC
  hosts: local
  tasks:
    - name: Stop instances
      ec2:
        region: "{{ aws_region }}"
        state: "stopped"
        instance_tags:
          Name: "{{ ec2_key_name }}"


