---
- name: AWS scrapy VPC
  hosts: local
  roles:
    - vpc
    - ec2

- name: Install scrapy and mongo
  hosts: scrapy_instances
  roles:
    - { role: scrapy, become: yes }
    - { role: mongodb, become: yes }


