---
- hosts: all
  gather_facts: true
  become: yes
  become_user: root
  become_method: sudo

  vars:
    site_name: "tutoriallinux"
    site_title: "Hope!"
    site_url: "www.tutoriallinux.com"

  tasks:
    - name: set timezone 
      timezone:
        name: Europe/London
    - name: install nginx
      package: name=nginx state=latest
    - name: create www dirs
      file: 
        path: "/var/www/{{ site_name }}"
        state: directory 
        mode: 0755
    - name: create nginx config
      template:
        src: "templates/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
      notify:
        - restart nginx
    - name: create nginx vhost config
      template:
        src: "templates/website.conf"
        dest: "/etc/nginx/conf.d/{{ site_name}}.conf"
      notify:
        - restart nginx
    - name: create website content
      template:
        src: "templates/index.html"
        dest: "/var/www/{{site_name}}/index.html"
      notify:
        - restart nginx
  handlers:
    - name: restart nginx
      service: 
        name: nginx
        state: restarted
