---
- hosts: all
  gather_facts: false
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  tasks:
    - name: install python2
      raw: test -e /usr/bin/python || (apt-get install -y python) 
    - name: install SSH keys
      authorized_key:
          user: root
          exclusive: no
          key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
